import { IQuestionItem } from './types.js';

export const STARTER_QUESTION_CATALOG: IQuestionItem[] = [
  // --- MATHEMATICS: NUMBER SYSTEMS ---
  {
    questionId: 'q_math_num_sys_1',
    conceptId: 'math_num_sys',
    subject: 'Mathematics',
    classLevel: 'Class 9-10',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'foundational',
    stem: 'Which of the following is an irrational number?',
    options: ['√4', '3/5', '√2', '0.75'],
    correctAnswer: '√2',
    explanation: '√2 cannot be expressed as a ratio of two integers p/q, hence it is irrational.',
    hint: 'Look for numbers whose decimal representations are non-terminating and non-recurring.',
    sourceType: 'NCERT Curriculum',
    sourceReference: 'Class 9 Math Chapter 1',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },
  {
    questionId: 'q_math_num_sys_2',
    conceptId: 'math_num_sys',
    subject: 'Mathematics',
    classLevel: 'Class 9-10',
    board: 'CBSE',
    questionType: 'true_false',
    difficulty: 'easy',
    stem: 'Every rational number is a real number.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    explanation: 'The set of real numbers consists of all rational and irrational numbers.',
    hint: 'Real numbers include both rational numbers and irrational numbers.',
    sourceType: 'NCERT Curriculum',
    sourceReference: 'Class 9 Math Chapter 1',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- MATHEMATICS: FRACTIONS ---
  {
    questionId: 'q_math_fractions_1',
    conceptId: 'math_fractions',
    subject: 'Mathematics',
    classLevel: 'Class 8-9',
    board: 'CBSE',
    questionType: 'numerical',
    difficulty: 'foundational',
    stem: 'Simplify 3/4 + 1/2. What is the value in decimal form?',
    options: [],
    correctAnswer: '1.25',
    explanation: '3/4 + 2/4 = 5/4 = 1.25.',
    hint: 'Convert fractions to a common denominator of 4.',
    sourceType: 'NCERT Curriculum',
    sourceReference: 'Class 8 Math Chapter 2',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- MATHEMATICS: PERCENTAGES ---
  {
    questionId: 'q_math_percentages_1',
    conceptId: 'math_percentages',
    subject: 'Mathematics',
    classLevel: 'Class 8-9',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'easy',
    stem: 'What is 15% of 200?',
    options: ['20', '30', '40', '15'],
    correctAnswer: '30',
    explanation: '15/100 * 200 = 30.',
    hint: 'Multiply 200 by 0.15.',
    sourceType: 'NCERT Curriculum',
    sourceReference: 'Class 8 Math Chapter 8',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- MATHEMATICS: ALGEBRA FUNDAMENTALS ---
  {
    questionId: 'q_math_algebra_1',
    conceptId: 'math_algebra_fund',
    subject: 'Mathematics',
    classLevel: 'Class 9',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'foundational',
    stem: 'Expand (a + b)²',
    options: ['a² + b²', 'a² + 2ab + b²', 'a² - 2ab + b²', '2a + 2b'],
    correctAnswer: 'a² + 2ab + b²',
    explanation: '(a + b)(a + b) = a² + ab + ba + b² = a² + 2ab + b².',
    hint: 'Multiply terms using the FOIL method.',
    sourceType: 'NCERT Curriculum',
    sourceReference: 'Class 9 Math Chapter 2',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- MATHEMATICS: LINEAR EQUATIONS ---
  {
    questionId: 'q_math_lin_eq_1',
    conceptId: 'math_linear_eq',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    questionType: 'numerical',
    difficulty: 'easy',
    stem: 'Solve for x: 2x + 5 = 15.',
    options: [],
    correctAnswer: '5',
    explanation: 'Subtract 5 from both sides: 2x = 10, so x = 5.',
    hint: 'Isolate x by subtracting 5 and dividing by 2.',
    sourceType: 'NCERT Curriculum',
    sourceReference: 'Class 10 Math Chapter 3',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },
  {
    questionId: 'q_math_lin_eq_2',
    conceptId: 'math_linear_eq',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'medium',
    stem: 'For what value of k will the pair of equations x + 2y = 3 and 3x + ky = 9 have infinitely many solutions?',
    options: ['3', '6', '9', '2'],
    correctAnswer: '6',
    explanation: 'For infinitely many solutions, a1/a2 = b1/b2 = c1/c2. Thus 1/3 = 2/k, which gives k = 6.',
    hint: 'Compare coefficients a1/a2 = b1/b2 = c1/c2.',
    sourceType: 'NCERT Curriculum',
    sourceReference: 'Class 10 Math Chapter 3',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- MATHEMATICS: POLYNOMIALS ---
  {
    questionId: 'q_math_poly_1',
    conceptId: 'math_polynomials',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'medium',
    stem: 'Find the zeroes of the polynomial p(x) = x² - 5x + 6.',
    options: ['2 and 3', '-2 and -3', '1 and 6', '-1 and -6'],
    correctAnswer: '2 and 3',
    explanation: 'x² - 5x + 6 = (x - 2)(x - 3) = 0, so zeroes are x = 2 and x = 3.',
    hint: 'Factorize the quadratic expression into (x - a)(x - b).',
    sourceType: 'NCERT Curriculum',
    sourceReference: 'Class 10 Math Chapter 2',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- MATHEMATICS: QUADRATIC EQUATIONS ---
  {
    questionId: 'q_math_quad_eq_1',
    conceptId: 'math_quadratic_eq',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'hard',
    stem: 'What is the discriminant of the quadratic equation 2x² - 4x + 3 = 0?',
    options: ['-8', '8', '4', '-4'],
    correctAnswer: '-8',
    explanation: 'Discriminant D = b² - 4ac = (-4)² - 4(2)(3) = 16 - 24 = -8.',
    hint: 'Use the formula D = b² - 4ac.',
    sourceType: 'NCERT Curriculum',
    sourceReference: 'Class 10 Math Chapter 4',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- MATHEMATICS: TRIGONOMETRY ---
  {
    questionId: 'q_math_trig_1',
    conceptId: 'math_trig',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'medium',
    stem: 'What is the value of sin(30°) + cos(60°)?',
    options: ['1', '0.5', '√3', '0'],
    correctAnswer: '1',
    explanation: 'sin(30°) = 0.5 and cos(60°) = 0.5. 0.5 + 0.5 = 1.',
    hint: 'sin(30°) = 1/2 and cos(60°) = 1/2.',
    sourceType: 'NCERT Curriculum',
    sourceReference: 'Class 10 Math Chapter 8',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- COMPUTER SCIENCE: PROGRAMMING FUNDAMENTALS ---
  {
    questionId: 'q_cs_prog_1',
    conceptId: 'cs_prog_fund',
    subject: 'Computer Science',
    classLevel: 'Class 9-10',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'foundational',
    stem: 'Which symbol is commonly used in flowcharts to represent a decision condition?',
    options: ['Diamond', 'Rectangle', 'Oval', 'Parallelogram'],
    correctAnswer: 'Diamond',
    explanation: 'A diamond symbol represents branching/decision steps in flowcharts.',
    hint: 'Think of the standard flowchart shape for IF-ELSE decisions.',
    sourceType: 'CBSE Curriculum',
    sourceReference: 'Class 9 CS Unit 1',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- COMPUTER SCIENCE: VARIABLES & DATA TYPES ---
  {
    questionId: 'q_cs_var_1',
    conceptId: 'cs_variables',
    subject: 'Computer Science',
    classLevel: 'Class 10',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'easy',
    stem: 'In Python, what data type is returned by the expression 5 / 2?',
    options: ['float', 'int', 'double', 'str'],
    correctAnswer: 'float',
    explanation: 'In Python 3, division / always produces a float (2.5).',
    hint: 'Normal division / yields decimal results in Python.',
    sourceType: 'Python Fundamentals',
    sourceReference: 'Class 11 Computer Science',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- COMPUTER SCIENCE: CONDITIONALS ---
  {
    questionId: 'q_cs_cond_1',
    conceptId: 'cs_conditions',
    subject: 'Computer Science',
    classLevel: 'Class 10',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'easy',
    stem: 'What will be printed by: if True and False: print("A") else: print("B")?',
    options: ['B', 'A', 'SyntaxError', 'Nothing'],
    correctAnswer: 'B',
    explanation: 'True AND False evaluates to False, so the else branch prints B.',
    hint: 'Logical AND requires both conditions to be True.',
    sourceType: 'Python Fundamentals',
    sourceReference: 'Class 10 CS Unit 2',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- COMPUTER SCIENCE: LOOPS ---
  {
    questionId: 'q_cs_loop_1',
    conceptId: 'cs_loops',
    subject: 'Computer Science',
    classLevel: 'Class 10',
    board: 'CBSE',
    questionType: 'numerical',
    difficulty: 'medium',
    stem: 'How many times will this loop execute? for i in range(2, 10, 2): pass',
    options: [],
    correctAnswer: '4',
    explanation: 'range(2, 10, 2) produces [2, 4, 6, 8], which is 4 iterations.',
    hint: 'List values starting at 2 up to but excluding 10, stepping by 2.',
    sourceType: 'Python Fundamentals',
    sourceReference: 'Class 10 CS Unit 2',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- SCIENCE: PHYSICS - LIGHT REFLECTION ---
  {
    questionId: 'q_phy_light_1',
    conceptId: 'phy_light_refl',
    subject: 'Physics',
    classLevel: 'Class 10',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'easy',
    stem: 'According to the law of reflection, the angle of incidence (i) is equal to:',
    options: ['Angle of reflection (r)', '90°', 'Angle of refraction', '0°'],
    correctAnswer: 'Angle of reflection (r)',
    explanation: 'The first law of reflection states that ∠i = ∠r.',
    hint: 'The incident ray and reflected ray form equal angles with the normal.',
    sourceType: 'NCERT Physics',
    sourceReference: 'Class 10 Science Chapter 10',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },

  // --- SCIENCE: CHEMISTRY - REACTIONS ---
  {
    questionId: 'q_chem_react_1',
    conceptId: 'chem_reactions',
    subject: 'Chemistry',
    classLevel: 'Class 10',
    board: 'CBSE',
    questionType: 'mcq',
    difficulty: 'medium',
    stem: 'What type of reaction is 2H₂ + O₂ → 2H₂O?',
    options: ['Combination Reaction', 'Decomposition Reaction', 'Displacement Reaction', 'Double Displacement'],
    correctAnswer: 'Combination Reaction',
    explanation: 'Two reactants combine to form a single product, which defines a combination reaction.',
    hint: 'Notice two simple substances combine to form one compound.',
    sourceType: 'NCERT Chemistry',
    sourceReference: 'Class 10 Science Chapter 1',
    generatedBy: 'human',
    verified: true,
    isActive: true,
  },
];
