import { IConceptDependencyEdge, IConceptNode } from './types.js';

export const STARTER_CONCEPTS_CATALOG: IConceptNode[] = [
  // --- MATHEMATICS ---
  {
    conceptId: 'math_num_sys',
    name: 'Number Systems',
    subject: 'Mathematics',
    classLevel: 'Class 9-10',
    board: 'CBSE',
    description: 'Real numbers, rational numbers, irrational numbers, and fundamental operations.',
    aliases: ['Real Numbers', 'Number Systems'],
    difficulty: 'beginner',
    category: 'Arithmetic',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jemh1=1-15',
  },
  {
    conceptId: 'math_fractions',
    name: 'Fractions & Decimals',
    subject: 'Mathematics',
    classLevel: 'Class 8-9',
    board: 'CBSE',
    description: 'Fractional representation, decimal expansion, and operations.',
    aliases: ['Fractions', 'Decimals'],
    difficulty: 'beginner',
    category: 'Arithmetic',
  },
  {
    conceptId: 'math_percentages',
    name: 'Percentages & Ratios',
    subject: 'Mathematics',
    classLevel: 'Class 8-9',
    board: 'CBSE',
    description: 'Percentage calculations, ratio comparison, and proportional reasoning.',
    aliases: ['Percentages', 'Ratios', 'Proportions'],
    difficulty: 'beginner',
    category: 'Arithmetic',
  },
  {
    conceptId: 'math_algebra_fund',
    name: 'Algebraic Fundamentals',
    subject: 'Mathematics',
    classLevel: 'Class 9',
    board: 'CBSE',
    description: 'Variables, constants, algebraic expressions, and basic identities.',
    aliases: ['Algebra', 'Algebraic Expressions'],
    difficulty: 'beginner',
    category: 'Algebra',
    officialSourceUrl: 'https://khanacademy.org/math/algebra',
  },
  {
    conceptId: 'math_linear_eq',
    name: 'Linear Equations in Two Variables',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'Graphical and algebraic solutions for pair of linear equations.',
    aliases: ['Linear Equations', 'Pair of Linear Equations'],
    difficulty: 'intermediate',
    category: 'Algebra',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jemh1=3-15',
  },
  {
    conceptId: 'math_polynomials',
    name: 'Polynomials',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'Degree of polynomials, zeroes of a polynomial, and division algorithm.',
    aliases: ['Polynomials', 'Zeros of Polynomials'],
    difficulty: 'intermediate',
    category: 'Algebra',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jemh1=2-15',
  },
  {
    conceptId: 'math_quadratic_eq',
    name: 'Quadratic Equations',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'Standard form, factorization, completing the square, and quadratic formula.',
    aliases: ['Quadratic Equations', 'Quadratic Formula'],
    difficulty: 'intermediate',
    category: 'Algebra',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jemh1=4-15',
  },
  {
    conceptId: 'math_functions',
    name: 'Functions & Relations',
    subject: 'Mathematics',
    classLevel: 'Class 11',
    board: 'CBSE',
    description: 'Sets, domain, range, and functional mapping.',
    aliases: ['Functions', 'Relations and Functions'],
    difficulty: 'advanced',
    category: 'Algebra',
  },
  {
    conceptId: 'math_coord_geom',
    name: 'Coordinate Geometry',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'Distance formula, section formula, and area of triangles.',
    aliases: ['Coordinate Geometry', 'Cartesian Plane'],
    difficulty: 'intermediate',
    category: 'Geometry',
  },
  {
    conceptId: 'math_trig',
    name: 'Introduction to Trigonometry',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'Trigonometric ratios, values for specific angles, and identities.',
    aliases: ['Trigonometry', 'Trig Ratios'],
    difficulty: 'intermediate',
    category: 'Trigonometry',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jemh1=8-15',
  },
  {
    conceptId: 'math_limits',
    name: 'Limits & Continuity',
    subject: 'Mathematics',
    classLevel: 'Class 11-12',
    board: 'CBSE',
    description: 'Concept of limits, left/right limits, and continuity.',
    aliases: ['Limits', 'Continuity'],
    difficulty: 'advanced',
    category: 'Calculus',
  },
  {
    conceptId: 'math_diff',
    name: 'Differentiation',
    subject: 'Mathematics',
    classLevel: 'Class 12',
    board: 'CBSE',
    description: 'Derivatives of composite, implicit, and trigonometric functions.',
    aliases: ['Differentiation', 'Derivatives'],
    difficulty: 'advanced',
    category: 'Calculus',
  },
  {
    conceptId: 'math_integ',
    name: 'Integration',
    subject: 'Mathematics',
    classLevel: 'Class 12',
    board: 'CBSE',
    description: 'Indefinite and definite integrals, substitution, and integration by parts.',
    aliases: ['Integration', 'Integrals'],
    difficulty: 'advanced',
    category: 'Calculus',
  },

  // --- COMPUTER SCIENCE ---
  {
    conceptId: 'cs_prog_fund',
    name: 'Programming Fundamentals',
    subject: 'Computer Science',
    classLevel: 'Class 9-10',
    board: 'CBSE',
    description: 'Algorithms, pseudocode, flowchart, and basic syntax.',
    aliases: ['Programming Fundamentals', 'Basic Coding'],
    difficulty: 'beginner',
    category: 'Programming',
  },
  {
    conceptId: 'cs_variables',
    name: 'Variables & Data Types',
    subject: 'Computer Science',
    classLevel: 'Class 9-10',
    board: 'CBSE',
    description: 'Memory storage, primitive types, and variable assignment.',
    aliases: ['Variables', 'Data Types'],
    difficulty: 'beginner',
    category: 'Programming',
  },
  {
    conceptId: 'cs_conditions',
    name: 'Control Flow & Conditionals',
    subject: 'Computer Science',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'If-else statements, boolean logic, and branching.',
    aliases: ['Conditionals', 'If Else'],
    difficulty: 'beginner',
    category: 'Programming',
  },
  {
    conceptId: 'cs_loops',
    name: 'Iteration & Loops',
    subject: 'Computer Science',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'For loops, while loops, and repetition patterns.',
    aliases: ['Loops', 'Iteration'],
    difficulty: 'intermediate',
    category: 'Programming',
  },
  {
    conceptId: 'cs_functions',
    name: 'Functions & Modular Code',
    subject: 'Computer Science',
    classLevel: 'Class 11',
    board: 'CBSE',
    description: 'Parameters, return values, scope, and reusability.',
    aliases: ['Functions', 'Methods'],
    difficulty: 'intermediate',
    category: 'Programming',
  },
  {
    conceptId: 'cs_arrays',
    name: 'Arrays & Lists',
    subject: 'Computer Science',
    classLevel: 'Class 11',
    board: 'CBSE',
    description: 'Sequential data collection, indexing, and iteration.',
    aliases: ['Arrays', 'Lists'],
    difficulty: 'intermediate',
    category: 'Data Structures',
  },
  {
    conceptId: 'cs_ds_algo',
    name: 'Data Structures & Algorithms',
    subject: 'Computer Science',
    classLevel: 'Class 12',
    board: 'CBSE',
    description: 'Stacks, queues, searching, and sorting algorithms.',
    aliases: ['Data Structures', 'Algorithms'],
    difficulty: 'advanced',
    category: 'Computer Science',
  },

  // --- PHYSICS ---
  {
    conceptId: 'phy_light_refl',
    name: 'Light - Reflection',
    subject: 'Physics',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'Spherical mirrors, mirror formula, and magnification.',
    aliases: ['Reflection', 'Mirrors'],
    difficulty: 'intermediate',
    category: 'Optics',
  },
  {
    conceptId: 'phy_light_refr',
    name: 'Light - Refraction',
    subject: 'Physics',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'Refractive index, lenses, lens formula, and power.',
    aliases: ['Refraction', 'Lenses'],
    difficulty: 'intermediate',
    category: 'Optics',
  },
  {
    conceptId: 'phy_electricity',
    name: 'Electricity & Ohm Law',
    subject: 'Physics',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'Electric current, potential difference, Ohm Law, and resistance.',
    aliases: ['Electricity', 'Ohms Law'],
    difficulty: 'intermediate',
    category: 'Electromagnetism',
  },

  // --- CHEMISTRY ---
  {
    conceptId: 'chem_reactions',
    name: 'Chemical Reactions & Equations',
    subject: 'Chemistry',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'Chemical equations, balancing, and types of chemical reactions.',
    aliases: ['Chemical Reactions', 'Balancing Equations'],
    difficulty: 'intermediate',
    category: 'Chemistry',
  },
  {
    conceptId: 'chem_acids_bases',
    name: 'Acids, Bases & Salts',
    subject: 'Chemistry',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'pH scale, neutralization, and chemical properties of acids & bases.',
    aliases: ['Acids Bases Salts', 'pH Scale'],
    difficulty: 'intermediate',
    category: 'Chemistry',
  },

  // --- BIOLOGY ---
  {
    conceptId: 'bio_life_proc',
    name: 'Life Processes',
    subject: 'Biology',
    classLevel: 'Class 10',
    board: 'CBSE',
    description: 'Nutrition, respiration, transportation, and excretion.',
    aliases: ['Life Processes', 'Respiration'],
    difficulty: 'intermediate',
    category: 'Biology',
  },

  // --- ENGLISH ---
  {
    conceptId: 'eng_tenses',
    name: 'English Tenses & Grammar',
    subject: 'English',
    classLevel: 'Class 9-10',
    board: 'CBSE',
    description: 'Past, present, future tenses and subject-verb agreement.',
    aliases: ['English Grammar', 'Tenses'],
    difficulty: 'beginner',
    category: 'Grammar',
  },
];

export const STARTER_CONCEPT_DEPENDENCIES: IConceptDependencyEdge[] = [
  // Math dependencies
  { prerequisiteConceptId: 'math_num_sys', dependentConceptId: 'math_fractions', dependencyType: 'foundational', strength: 0.9, confidence: 0.95 },
  { prerequisiteConceptId: 'math_fractions', dependentConceptId: 'math_percentages', dependencyType: 'foundational', strength: 0.9, confidence: 0.95 },
  { prerequisiteConceptId: 'math_num_sys', dependentConceptId: 'math_algebra_fund', dependencyType: 'prerequisite', strength: 0.95, confidence: 0.98 },
  { prerequisiteConceptId: 'math_algebra_fund', dependentConceptId: 'math_linear_eq', dependencyType: 'prerequisite', strength: 0.95, confidence: 0.98 },
  { prerequisiteConceptId: 'math_algebra_fund', dependentConceptId: 'math_polynomials', dependencyType: 'prerequisite', strength: 0.9, confidence: 0.95 },
  { prerequisiteConceptId: 'math_linear_eq', dependentConceptId: 'math_quadratic_eq', dependencyType: 'prerequisite', strength: 0.95, confidence: 0.98 },
  { prerequisiteConceptId: 'math_polynomials', dependentConceptId: 'math_quadratic_eq', dependencyType: 'foundational', strength: 0.85, confidence: 0.9 },
  { prerequisiteConceptId: 'math_quadratic_eq', dependentConceptId: 'math_functions', dependencyType: 'prerequisite', strength: 0.9, confidence: 0.95 },
  { prerequisiteConceptId: 'math_linear_eq', dependentConceptId: 'math_coord_geom', dependencyType: 'prerequisite', strength: 0.85, confidence: 0.9 },
  { prerequisiteConceptId: 'math_functions', dependentConceptId: 'math_limits', dependencyType: 'prerequisite', strength: 0.95, confidence: 0.98 },
  { prerequisiteConceptId: 'math_limits', dependentConceptId: 'math_diff', dependencyType: 'prerequisite', strength: 0.95, confidence: 0.98 },
  { prerequisiteConceptId: 'math_diff', dependentConceptId: 'math_integ', dependencyType: 'prerequisite', strength: 0.95, confidence: 0.98 },

  // CS dependencies
  { prerequisiteConceptId: 'cs_prog_fund', dependentConceptId: 'cs_variables', dependencyType: 'prerequisite', strength: 0.95, confidence: 0.98 },
  { prerequisiteConceptId: 'cs_variables', dependentConceptId: 'cs_conditions', dependencyType: 'prerequisite', strength: 0.95, confidence: 0.98 },
  { prerequisiteConceptId: 'cs_conditions', dependentConceptId: 'cs_loops', dependencyType: 'prerequisite', strength: 0.95, confidence: 0.98 },
  { prerequisiteConceptId: 'cs_loops', dependentConceptId: 'cs_functions', dependencyType: 'prerequisite', strength: 0.9, confidence: 0.95 },
  { prerequisiteConceptId: 'cs_functions', dependentConceptId: 'cs_arrays', dependencyType: 'prerequisite', strength: 0.9, confidence: 0.95 },
  { prerequisiteConceptId: 'cs_arrays', dependentConceptId: 'cs_ds_algo', dependencyType: 'prerequisite', strength: 0.95, confidence: 0.98 },

  // Physics dependencies
  { prerequisiteConceptId: 'phy_light_refl', dependentConceptId: 'phy_light_refr', dependencyType: 'prerequisite', strength: 0.9, confidence: 0.95 },

  // Chemistry dependencies
  { prerequisiteConceptId: 'chem_reactions', dependentConceptId: 'chem_acids_bases', dependencyType: 'prerequisite', strength: 0.85, confidence: 0.9 },
];
