import { Router } from 'express';
import healthRoutes from './health.routes.js';
import authRoutes from './auth.routes.js';
import studentRoutes from './student.routes.js';
import teacherRoutes from './teacher.routes.js';
import subjectRoutes from './subject.routes.js';
import topicRoutes from './topic.routes.js';
import scholarshipRoutes from './scholarship.routes.js';
import tutorRoutes from './tutor.routes.js';
import ragRoutes from './rag.routes.js';
import studyPlanRoutes from './study-plan.routes.js';
import mistakeReviewRoutes from './mistake-review.routes.js';
import practiceHistoryRoutes from './practice-history.routes.js';
import { teacherInterventionRouter, studentInterventionRouter } from './intervention.routes.js';
import learningCoachRoutes from './learning-coach.routes.js';
import { parentRouter, studentParentLinkRouter } from './parent.routes.js';
import { studentGoalRouter, achievementRouter } from './student-goal.routes.js';
import examPreparationRoutes from './exam-preparation.routes.js';
import careerRoutes from './career.routes.js';
import notificationRoutes from './notification.routes.js';
import analyticsRoutes from './analytics.routes.js';
import riskRoutes from './risk.routes.js';
import teacherCopilotRoutes from './teacher-copilot.routes.js';
import parentCopilotRoutes from './parent-copilot.routes.js';
import studentMentorRoutes from './student-mentor.routes.js';
import learningAnalyticsRoutes from './learning-analytics.routes.js';
import studyPlannerRoutes from './study-planner.routes.js';
import resourceRecommendationRoutes from './resource-recommendation.routes.js';
import revisionRoutes from './revision.routes.js';
import knowledgeGraphRoutes from './knowledge-graph.routes.js';
import adaptiveAssessmentRoutes from './adaptive-assessment.routes.js';
import learningPathRoutes from './learning-path.routes.js';
import studyMaterialRoutes from './study-material.routes.js';

const router = Router();

router.use('/', healthRoutes);
router.use('/auth', authRoutes);
router.use('/teacher/copilot', teacherCopilotRoutes);
router.use('/parent/copilot', parentCopilotRoutes);
router.use('/student/mentor', studentMentorRoutes);
router.use('/student/analytics', learningAnalyticsRoutes);
router.use('/student/study-planner', studyPlannerRoutes);
router.use('/student/resources', resourceRecommendationRoutes);
router.use('/student/revision', revisionRoutes);
router.use('/student/assessments', adaptiveAssessmentRoutes);
router.use('/student/learning-path', learningPathRoutes);
router.use('/student/study-material', studyMaterialRoutes);
router.use('/knowledge-graph', knowledgeGraphRoutes);
router.use('/risk', riskRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/notifications', notificationRoutes);
router.use('/parent', parentRouter);
router.use('/student/parent-link', studentParentLinkRouter);
router.use('/student/learning-coach', learningCoachRoutes);
router.use('/student/goals', studentGoalRouter);
router.use('/student/achievements', achievementRouter);
router.use('/student/exams', examPreparationRoutes);
router.use('/student/career', careerRoutes);
router.use('/student/study-plan', studyPlanRoutes);
router.use('/student/practice/history', practiceHistoryRoutes);
router.use('/student/practice', mistakeReviewRoutes);
router.use('/student/interventions', studentInterventionRouter);
router.use('/student', studentRoutes);
router.use('/teacher/interventions', teacherInterventionRouter);
router.use('/teacher', teacherRoutes);
router.use('/subjects', subjectRoutes);
router.use('/topics', topicRoutes);
router.use('/scholarships', scholarshipRoutes);
router.use('/tutor', tutorRoutes);
router.use('/rag', ragRoutes);

export default router;
