import { IResourceItem } from './types.js';

export const STARTER_RESOURCE_CATALOG: IResourceItem[] = [
  // --- MATHEMATICS: LINEAR EQUATIONS ---
  {
    resourceId: 'res_math_lin_1',
    title: 'Mastering Pair of Linear Equations in Two Variables',
    description: 'Comprehensive guide covering graphical method, substitution, and elimination techniques with step-by-step NCERT solutions.',
    resourceType: 'article',
    subject: 'Mathematics',
    topic: 'Linear Equations',
    conceptId: 'math_linear_eq',
    classLevel: 'Class 10',
    board: 'CBSE',
    difficulty: 'medium',
    estimatedMinutes: 12,
    provider: 'NCERT Educational Library',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jemh1=3-15',
    tags: ['algebra', 'linear equations', 'cbse', 'class 10'],
    language: 'English',
    isVerified: true,
    active: true,
  },
  {
    resourceId: 'res_math_lin_2',
    title: 'Linear Equations Practice Worksheet & Problem Sets',
    description: 'Interactive problem set with 15 solved practice questions testing algebraic and graphical solutions.',
    resourceType: 'worksheet',
    subject: 'Mathematics',
    topic: 'Linear Equations',
    conceptId: 'math_linear_eq',
    classLevel: 'Class 10',
    board: 'CBSE',
    difficulty: 'easy',
    estimatedMinutes: 10,
    provider: 'BharatEdu Practice Hub',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jemh1=3-15',
    tags: ['worksheet', 'practice', 'algebra'],
    language: 'English',
    isVerified: true,
    active: true,
  },

  // --- MATHEMATICS: ALGEBRA FUNDAMENTALS ---
  {
    resourceId: 'res_math_alg_1',
    title: 'Foundational Algebraic Identities & Polynomial Operations',
    description: 'Core concepts video and text notes explaining expansion of identities and factorization.',
    resourceType: 'notes',
    subject: 'Mathematics',
    topic: 'Algebraic Fundamentals',
    conceptId: 'math_algebra_fund',
    classLevel: 'Class 9',
    board: 'CBSE',
    difficulty: 'foundational',
    estimatedMinutes: 10,
    provider: 'Khan Academy Open Repository',
    officialSourceUrl: 'https://khanacademy.org/math/algebra',
    tags: ['foundational', 'algebra', 'identities'],
    language: 'English',
    isVerified: true,
    active: true,
  },

  // --- MATHEMATICS: QUADRATIC EQUATIONS ---
  {
    resourceId: 'res_math_quad_1',
    title: 'Quadratic Equations Formula & Discriminant Analysis',
    description: 'Detailed reference guide explaining quadratic formula, nature of roots, and real-life word problem applications.',
    resourceType: 'reference',
    subject: 'Mathematics',
    topic: 'Quadratic Equations',
    conceptId: 'math_quadratic_eq',
    classLevel: 'Class 10',
    board: 'CBSE',
    difficulty: 'hard',
    estimatedMinutes: 20,
    provider: 'NCERT Educational Library',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jemh1=4-15',
    tags: ['quadratic', 'discriminant', 'class 10'],
    language: 'English',
    isVerified: true,
    active: true,
  },

  // --- COMPUTER SCIENCE: VARIABLES & CONTROL FLOW ---
  {
    resourceId: 'res_cs_var_1',
    title: 'Python Data Types & Variable Scope Tutorial',
    description: 'Learn memory allocation, dynamic typing, and variable scope rules in Python programming.',
    resourceType: 'article',
    subject: 'Computer Science',
    topic: 'Variables & Data Types',
    conceptId: 'cs_variables',
    classLevel: 'Class 10',
    board: 'CBSE',
    difficulty: 'easy',
    estimatedMinutes: 10,
    provider: 'Python Documentation',
    tags: ['python', 'variables', 'computer science'],
    language: 'English',
    isVerified: true,
    active: true,
  },

  // --- SCIENCE: PHYSICS - LIGHT REFLECTION ---
  {
    resourceId: 'res_phy_light_1',
    title: 'Ray Diagrams for Spherical Mirrors & Mirror Formula',
    description: 'Visual study notes on concave and convex mirror ray diagrams and sign convention rules.',
    resourceType: 'notes',
    subject: 'Physics',
    topic: 'Light Reflection',
    conceptId: 'phy_light_refl',
    classLevel: 'Class 10',
    board: 'CBSE',
    difficulty: 'medium',
    estimatedMinutes: 15,
    provider: 'NCERT Science Library',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jesc1=10-16',
    tags: ['physics', 'optics', 'mirrors'],
    language: 'English',
    isVerified: true,
    active: true,
  },

  // --- SCIENCE: CHEMISTRY - CHEMICAL REACTIONS ---
  {
    resourceId: 'res_chem_react_1',
    title: 'Balancing Chemical Equations & Reaction Types',
    description: 'Step-by-step guide to balancing chemical reactions, redox reactions, and precipitation.',
    resourceType: 'article',
    subject: 'Chemistry',
    topic: 'Chemical Reactions',
    conceptId: 'chem_reactions',
    classLevel: 'Class 10',
    board: 'CBSE',
    difficulty: 'medium',
    estimatedMinutes: 15,
    provider: 'NCERT Science Library',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jesc1=1-16',
    tags: ['chemistry', 'reactions', 'equations'],
    language: 'English',
    isVerified: true,
    active: true,
  },
];
