import { ILearningResourceDTO } from './types.js';

export const VERIFIED_RESOURCE_CATALOG: ILearningResourceDTO[] = [
  {
    resourceId: 'res_math_ncert_alg_10',
    title: 'NCERT Class 10 Mathematics — Chapter 3: Pair of Linear Equations',
    description: 'Official NCERT textbook chapter covering substitution, elimination, and graphical solutions.',
    resourceType: 'textbook',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    topicIds: ['Linear Equations'],
    conceptIds: ['math_linear_eq', 'math_algebra_fund'],
    skillIds: ['algebra_solving', 'equation_graphing'],
    careerIds: ['software_engineer', 'data_scientist'],
    difficulty: 'beginner',
    estimatedMinutes: 30,
    language: 'English',
    provider: 'NCERT',
    officialSource: 'NCERT Official Portal',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jemh1=3-15',
    url: 'https://ncert.nic.in/textbook.php?jemh1=3-15',
    qualityScore: 98,
    isVerified: true,
    tags: ['ncert', 'cbse', 'class10', 'math', 'linear_equations'],
  },
  {
    resourceId: 'res_math_khan_quad_10',
    title: 'Khan Academy — Solving Quadratic Equations by Factoring & Formula',
    description: 'Interactive video lessons and practice exercises on quadratic equations and discriminant analysis.',
    resourceType: 'video',
    subject: 'Mathematics',
    classLevel: 'Class 10',
    board: 'CBSE',
    topicIds: ['Quadratic Equations'],
    conceptIds: ['math_quadratic_eq', 'math_algebra_fund'],
    skillIds: ['quadratic_factoring', 'discriminant_analysis'],
    careerIds: ['data_scientist', 'ai_engineer'],
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    language: 'English',
    provider: 'Khan Academy',
    officialSource: 'Khan Academy Official',
    officialSourceUrl: 'https://www.khanacademy.org/math/in-in-grade-10-math/in-in-quadratic-equations-icse',
    url: 'https://www.khanacademy.org/math/in-in-grade-10-math/in-in-quadratic-equations-icse',
    qualityScore: 95,
    isVerified: true,
    tags: ['khanacademy', 'math', 'quadratic_equations', 'interactive'],
  },
  {
    resourceId: 'res_phy_diksha_light_10',
    title: 'DIKSHA Portal — Reflection & Refraction of Light Interactive Notes',
    description: 'Ministry of Education DIKSHA digital resource for concave and convex mirrors.',
    resourceType: 'notes',
    subject: 'Physics',
    classLevel: 'Class 10',
    board: 'CBSE',
    topicIds: ['Light Reflection'],
    conceptIds: ['phy_light_refl'],
    skillIds: ['ray_diagrams', 'optics_formula'],
    careerIds: ['hardware_engineer', 'optical_engineer'],
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    language: 'English',
    provider: 'DIKSHA Portal',
    officialSource: 'DIKSHA Official Portal',
    officialSourceUrl: 'https://diksha.gov.in/explore',
    url: 'https://diksha.gov.in/explore',
    qualityScore: 96,
    isVerified: true,
    tags: ['diksha', 'gov_in', 'physics', 'optics', 'class10'],
  },
  {
    resourceId: 'res_cs_python_org_docs',
    title: 'Python Official Documentation — Tutorial & Data Structures',
    description: 'Official Python 3 documentation covering variables, control flow, functions, lists, and dicts.',
    resourceType: 'documentation',
    subject: 'Computer Science',
    classLevel: 'Class 10',
    board: 'CBSE',
    topicIds: ['Variables & Data Types', 'Python Control Flow'],
    conceptIds: ['cs_variables', 'cs_functions'],
    skillIds: ['python_programming', 'algorithm_design'],
    careerIds: ['ai_engineer', 'software_engineer'],
    difficulty: 'beginner',
    estimatedMinutes: 30,
    language: 'English',
    provider: 'Python Software Foundation',
    officialSource: 'Python.org Official',
    officialSourceUrl: 'https://docs.python.org/3/tutorial/',
    url: 'https://docs.python.org/3/tutorial/',
    qualityScore: 99,
    isVerified: true,
    tags: ['python', 'official_docs', 'computer_science', 'coding'],
  },
  {
    resourceId: 'res_cs_mdn_web_dev',
    title: 'MDN Web Docs — HTML & JavaScript Fundamentals',
    description: 'Mozilla Developer Network comprehensive guide to web development standards.',
    resourceType: 'article',
    subject: 'Computer Science',
    classLevel: 'Class 10',
    board: 'CBSE',
    topicIds: ['Web Development', 'JavaScript Basics'],
    conceptIds: ['cs_web_dev'],
    skillIds: ['html_css', 'javascript'],
    careerIds: ['web_developer', 'software_engineer'],
    difficulty: 'beginner',
    estimatedMinutes: 25,
    language: 'English',
    provider: 'Mozilla MDN',
    officialSource: 'MDN Web Docs',
    officialSourceUrl: 'https://developer.mozilla.org/en-US/docs/Learn',
    url: 'https://developer.mozilla.org/en-US/docs/Learn',
    qualityScore: 97,
    isVerified: true,
    tags: ['mdn', 'web_dev', 'javascript', 'html'],
  },
  {
    resourceId: 'res_chem_ncert_react_10',
    title: 'NCERT Class 10 Chemistry — Chemical Reactions & Equations',
    description: 'NCERT official chapter explaining combination, decomposition, displacement, and redox reactions.',
    resourceType: 'textbook',
    subject: 'Chemistry',
    classLevel: 'Class 10',
    board: 'CBSE',
    topicIds: ['Chemical Reactions'],
    conceptIds: ['chem_reactions'],
    skillIds: ['equation_balancing', 'reaction_types'],
    careerIds: ['chemical_engineer', 'doctor'],
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    language: 'English',
    provider: 'NCERT',
    officialSource: 'NCERT Official Portal',
    officialSourceUrl: 'https://ncert.nic.in/textbook.php?jesc1=1-16',
    url: 'https://ncert.nic.in/textbook.php?jesc1=1-16',
    qualityScore: 98,
    isVerified: true,
    tags: ['ncert', 'chemistry', 'class10', 'cbse'],
  },
  {
    resourceId: 'res_nptel_cs_intro',
    title: 'NPTEL SWAYAM — Introduction to Programming in C & Python',
    description: 'IIT faculty video course under Government of India SWAYAM initiative.',
    resourceType: 'course',
    subject: 'Computer Science',
    classLevel: 'Class 11',
    board: 'CBSE',
    topicIds: ['Programming Fundamentals'],
    conceptIds: ['cs_variables', 'cs_functions'],
    skillIds: ['problem_solving', 'structured_programming'],
    careerIds: ['ai_engineer', 'software_engineer'],
    difficulty: 'intermediate',
    estimatedMinutes: 45,
    language: 'English',
    provider: 'NPTEL / IIT Madras',
    officialSource: 'SWAYAM NPTEL Official',
    officialSourceUrl: 'https://nptel.ac.in/courses',
    url: 'https://nptel.ac.in/courses',
    qualityScore: 96,
    isVerified: true,
    tags: ['nptel', 'swayam', 'iit', 'programming'],
  },
];
