import { ResourceCandidate } from './types.js';

export const STARTER_RESOURCE_CATALOG: ResourceCandidate[] = [
  {
    resourceId: 'res_ncert_math_algebra',
    title: 'NCERT Class 10 Mathematics - Chapter 4 Quadratic Equations',
    description: 'Official NCERT textbook chapter covering methods of solving quadratic equations, discriminant, and nature of roots.',
    resourceType: 'ncert',
    subject: 'Mathematics',
    topicId: 'Algebra',
    conceptId: 'math_quadratic_eq',
    classLevel: '10th',
    board: 'CBSE',
    language: 'en',
    difficulty: 'medium',
    estimatedMinutes: 30,
    provider: 'NCERT',
    author: 'NCERT Textbook Committee',
    url: 'https://ncert.nic.in/textbook.php',
    thumbnailUrl: null,
    official: true,
    verified: true,
    tags: ['ncert', 'quadratic_equations', 'algebra', 'cbse_10'],
    prerequisites: ['math_factorization', 'math_linear_eq'],
    careerTags: ['engineering', 'data_science'],
    examTags: ['cbse_board', 'jee_foundation'],
    qualityScore: 98,
    popularityScore: 92,
    freshnessScore: 95,
  },
  {
    resourceId: 'res_ncert_factorization',
    title: 'NCERT Class 9 Mathematics - Polynomials & Factorization',
    description: 'Official NCERT foundational chapter explaining algebraic identities, splitting the middle term, and factor theorem.',
    resourceType: 'ncert',
    subject: 'Mathematics',
    topicId: 'Algebra',
    conceptId: 'math_factorization',
    classLevel: '9th',
    board: 'CBSE',
    language: 'en',
    difficulty: 'easy',
    estimatedMinutes: 20,
    provider: 'NCERT',
    author: 'NCERT Textbook Committee',
    url: 'https://ncert.nic.in/textbook.php',
    thumbnailUrl: null,
    official: true,
    verified: true,
    tags: ['ncert', 'factorization', 'prerequisite', 'cbse_9'],
    prerequisites: [],
    careerTags: ['engineering'],
    examTags: ['cbse_board'],
    qualityScore: 95,
    popularityScore: 88,
    freshnessScore: 90,
  },
  {
    resourceId: 'res_python_official_tutorial',
    title: 'Official Python 3 Documentation - Language Tutorial',
    description: 'Official Python reference guide for syntax, control flow, functions, and data structures.',
    resourceType: 'documentation',
    subject: 'Computer Science',
    topicId: 'Python',
    conceptId: 'cs_python_basics',
    classLevel: '11th',
    board: 'CBSE',
    language: 'en',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    provider: 'Python Software Foundation',
    author: 'Guido van Rossum & Python Community',
    url: 'https://docs.python.org/3/tutorial/index.html',
    thumbnailUrl: null,
    official: true,
    verified: true,
    tags: ['python', 'coding', 'official_docs', 'basics'],
    prerequisites: [],
    careerTags: ['software_engineering', 'data_science', 'ai'],
    examTags: ['cbse_cs_11', 'cbse_ip_12'],
    qualityScore: 99,
    popularityScore: 95,
    freshnessScore: 98,
  },
  {
    resourceId: 'res_physics_motion_notes',
    title: 'NCERT Class 9 Physics - Motion & Kinematic Equations',
    description: 'Fundamental concepts of velocity, acceleration, distance-time graphs, and equations of motion.',
    resourceType: 'textbook',
    subject: 'Physics',
    topicId: 'Kinematics',
    conceptId: 'physics_motion_laws',
    classLevel: '9th',
    board: 'CBSE',
    language: 'en',
    difficulty: 'medium',
    estimatedMinutes: 25,
    provider: 'NCERT',
    author: 'NCERT Science Editorial Board',
    url: 'https://ncert.nic.in/textbook.php',
    thumbnailUrl: null,
    official: true,
    verified: true,
    tags: ['physics', 'motion', 'kinematics'],
    prerequisites: ['math_linear_eq'],
    careerTags: ['engineering', 'robotics'],
    examTags: ['cbse_science', 'neet_foundation'],
    qualityScore: 94,
    popularityScore: 85,
    freshnessScore: 92,
  },
  {
    resourceId: 'res_chem_periodic_table',
    title: 'NCERT Class 10 Chemistry - Periodic Classification of Elements',
    description: 'Modern periodic law, trends in atomic radius, valency, metallic and non-metallic properties across periods and groups.',
    resourceType: 'notes',
    subject: 'Chemistry',
    topicId: 'Periodic Table',
    conceptId: 'chem_periodic_trends',
    classLevel: '10th',
    board: 'CBSE',
    language: 'en',
    difficulty: 'medium',
    estimatedMinutes: 20,
    provider: 'NCERT',
    author: 'NCERT Science Editorial Board',
    url: 'https://ncert.nic.in/textbook.php',
    thumbnailUrl: null,
    official: true,
    verified: true,
    tags: ['chemistry', 'periodic_table', 'trends'],
    prerequisites: [],
    careerTags: ['medicine', 'biotechnology', 'chemical_engineering'],
    examTags: ['cbse_board', 'neet_foundation'],
    qualityScore: 93,
    popularityScore: 80,
    freshnessScore: 91,
  },
  {
    resourceId: 'res_internal_algebra_practice',
    title: 'Targeted Practice Quiz - Quadratic Equations & Discriminant',
    description: 'Interactive diagnostic practice problem set with step-by-step adaptive feedback.',
    resourceType: 'practice',
    subject: 'Mathematics',
    topicId: 'Algebra',
    conceptId: 'math_quadratic_eq',
    classLevel: '10th',
    board: 'CBSE',
    language: 'en',
    difficulty: 'medium',
    estimatedMinutes: 15,
    provider: 'BharatEdu AI Engine',
    author: 'BharatEdu AI Content Team',
    url: null, // Internal native interactive practice
    thumbnailUrl: null,
    official: true,
    verified: true,
    tags: ['practice', 'quiz', 'internal'],
    prerequisites: ['math_factorization'],
    careerTags: ['engineering'],
    examTags: ['cbse_board'],
    qualityScore: 96,
    popularityScore: 90,
    freshnessScore: 100,
  },
];
