import { LearningResource } from './types.js';

export const VERIFIED_RESOURCE_CATALOG: LearningResource[] = [
  {
    resourceId: 'res_ncert_math_9_01',
    title: 'NCERT Class 9 Mathematics Chapter 1: Number Systems',
    description: 'Official NCERT textbook chapter covering Rational Numbers, Irrational Numbers, Real Numbers and their Decimal Expansions.',
    resourceType: 'chapter',
    subject: 'Mathematics',
    topic: 'Number Systems',
    conceptId: 'concept_num_sys_01',
    classLevel: 9,
    board: 'CBSE',
    language: 'en',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    provider: 'NCERT',
    officialSource: 'NCERT Official Portal',
    sourceUrl: 'https://ncert.nic.in/textbook.php?iemh1=1-15',
    thumbnailUrl: 'https://ncert.nic.in/assets/images/ncert_logo.png',
    tags: ['ncert', 'cbse', 'number_systems', 'rational_numbers', 'foundations'],
    prerequisites: [],
    learningObjectives: ['Understand rational and irrational numbers', 'Represent real numbers on number line'],
    careerRelevance: ['Data Science', 'Engineering', 'STEM Fundamentals'],
    examRelevance: ['CBSE Board Exam', 'NTSE', 'Mathematics Olympiad'],
    isVerified: true,
    isActive: true,
  },
  {
    resourceId: 'res_ncert_math_10_02',
    title: 'NCERT Class 10 Mathematics Chapter 2: Polynomials',
    description: 'Comprehensive guide to Geometrical Meaning of Zeroes of a Polynomial and Relationship between Zeroes and Coefficients.',
    resourceType: 'textbook',
    subject: 'Mathematics',
    topic: 'Polynomials',
    conceptId: 'concept_poly_02',
    classLevel: 10,
    board: 'CBSE',
    language: 'en',
    difficulty: 'intermediate',
    estimatedMinutes: 45,
    provider: 'NCERT',
    officialSource: 'NCERT Official Portal',
    sourceUrl: 'https://ncert.nic.in/textbook.php?jemh1=2-15',
    thumbnailUrl: 'https://ncert.nic.in/assets/images/ncert_logo.png',
    tags: ['ncert', 'algebra', 'polynomials', 'quadratic_equations'],
    prerequisites: ['concept_num_sys_01'],
    learningObjectives: ['Find zeroes of quadratic polynomials', 'Verify relationship between coefficients and roots'],
    careerRelevance: ['Software Engineering', 'Financial Modeling', 'Data Science'],
    examRelevance: ['CBSE Class 10 Board Exam', 'JEE Main Foundation'],
    isVerified: true,
    isActive: true,
  },
  {
    resourceId: 'res_diksha_sci_10_01',
    title: 'DIKSHA Interactive Video: Chemical Reactions & Equations',
    description: 'Official Ministry of Education DIKSHA module detailing chemical combination, decomposition, displacement, and redox reactions.',
    resourceType: 'video',
    subject: 'Science',
    topic: 'Chemical Reactions and Equations',
    conceptId: 'concept_chem_react_01',
    classLevel: 10,
    board: 'CBSE',
    language: 'en',
    difficulty: 'beginner',
    estimatedMinutes: 20,
    provider: 'DIKSHA Portal',
    officialSource: 'PM eVidya DIKSHA Platform',
    sourceUrl: 'https://diksha.gov.in/explore-course/course/do_313074',
    thumbnailUrl: 'https://diksha.gov.in/assets/images/diksha_logo.png',
    tags: ['diksha', 'chemistry', 'reactions', 'experiments', 'pm_evidya'],
    prerequisites: [],
    learningObjectives: ['Balance chemical equations', 'Identify combination and redox reactions'],
    careerRelevance: ['Chemical Engineering', 'Medicine & Biotechnology', 'Pharmacy'],
    examRelevance: ['CBSE Class 10 Science Board Exam', 'NEET Foundation'],
    isVerified: true,
    isActive: true,
  },
  {
    resourceId: 'res_nios_phy_12_01',
    title: 'NIOS Senior Secondary Physics: Electrostatics & Electric Charges',
    description: 'National Institute of Open Schooling study guide on Coulomb Law, Electric Field, and Electric Potential.',
    resourceType: 'article',
    subject: 'Physics',
    topic: 'Electrostatics',
    conceptId: 'concept_electrostatics_01',
    classLevel: 12,
    board: 'NIOS',
    language: 'en',
    difficulty: 'intermediate',
    estimatedMinutes: 35,
    provider: 'NIOS',
    officialSource: 'NIOS Official Learning Portal',
    sourceUrl: 'https://nios.ac.in/online-course-material/sr-secondary-courses/physics-(312).aspx',
    thumbnailUrl: 'https://nios.ac.in/assets/images/logo.png',
    tags: ['nios', 'physics', 'electrostatics', 'coulomb_law'],
    prerequisites: ['concept_num_sys_01'],
    learningObjectives: ['Calculate force between point charges', 'Determine electric flux using Gauss Law'],
    careerRelevance: ['Electrical Engineering', 'Robotics', 'Applied Physics'],
    examRelevance: ['JEE Main', 'JEE Advanced', 'CUET Science'],
    isVerified: true,
    isActive: true,
  },
  {
    resourceId: 'res_diksha_math_practice_01',
    title: 'CBSE DIKSHA Question Bank: Algebraic Fractions & Rational Expressions',
    description: 'Verified practice problem set with step-by-step solutions for denominator manipulation and simplification.',
    resourceType: 'practice_set',
    subject: 'Mathematics',
    topic: 'Fractions & Rational Expressions',
    conceptId: 'concept_fractions_01',
    classLevel: 9,
    board: 'CBSE',
    language: 'en',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    provider: 'CBSE DIKSHA',
    officialSource: 'CBSE Academic Official Portal',
    sourceUrl: 'https://cbseacademic.nic.in/qb_class9.html',
    thumbnailUrl: 'https://cbseacademic.nic.in/images/cbse_logo.png',
    tags: ['practice', 'fractions', 'remediation', 'cbse_question_bank'],
    prerequisites: [],
    learningObjectives: ['Simplify rational fractions', 'Find common denominators in algebraic terms'],
    careerRelevance: ['Engineering', 'Architecture', 'Computer Science'],
    examRelevance: ['CBSE Class 9 Term Assessment', 'Math Olympiad'],
    isVerified: true,
    isActive: true,
  },
  {
    resourceId: 'res_ncert_hi_math_10_01',
    title: 'NCERT कक्षा 10 गणित अध्याय 1: वास्तविक संख्याएं (Hindi Edition)',
    description: 'एनसीईआरटी द्वारा प्रमाणित वास्तविक संख्याएं, यूक्लिड विभाजन प्रमेयिका और अंकगणित की आधारभूत प्रमेय।',
    resourceType: 'chapter',
    subject: 'Mathematics',
    topic: 'Real Numbers',
    conceptId: 'concept_real_num_hi',
    classLevel: 10,
    board: 'CBSE',
    language: 'hi',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    provider: 'NCERT',
    officialSource: 'NCERT Hindi Portal',
    sourceUrl: 'https://ncert.nic.in/textbook.php?jh1=1-15',
    thumbnailUrl: 'https://ncert.nic.in/assets/images/ncert_logo.png',
    tags: ['ncert_hindi', 'real_numbers', 'cbse_hindi', 'math'],
    prerequisites: [],
    learningObjectives: ['यूक्लिड विभाजन प्रमेयिका का उपयोग करें', 'अभाज्य गुणनखंडन विधि सीखें'],
    careerRelevance: ['Engineering', 'Education', 'Science'],
    examRelevance: ['CBSE Hindi Medium Board Exam'],
    isVerified: true,
    isActive: true,
  },
  {
    resourceId: 'res_ncert_gu_math_10_01',
    title: 'NCERT ધોરણ 10 ગણિત પ્રકરણ 1: વાસ્તવિક સંખ્યાઓ (Gujarati Edition)',
    description: 'ગુજરાત શિક્ષણ બોર્ડ અને NCERT માન્ય વાસ્તવિક સંખ્યાઓ અને યુક્લિડનું ભાગાકારનું પૂર્વપ્રમેય.',
    resourceType: 'chapter',
    subject: 'Mathematics',
    topic: 'Real Numbers',
    conceptId: 'concept_real_num_gu',
    classLevel: 10,
    board: 'GSEB',
    language: 'gu',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    provider: 'NCERT / GSEB',
    officialSource: 'Gujarat State Board Textbooks',
    sourceUrl: 'https://gsbse.org/textbooks/maths_std10_gu.pdf',
    thumbnailUrl: 'https://gsbse.org/assets/logo.png',
    tags: ['gseb', 'gujarati_medium', 'real_numbers'],
    prerequisites: [],
    learningObjectives: ['ગુસાઅ અને લસાઅ શોધો', 'સંખ્યાઓનું અવિભાજ્ય અવયવીકરણ'],
    careerRelevance: ['Engineering', 'Commerce', 'Science'],
    examRelevance: ['GSEB Board Exam Class 10'],
    isVerified: true,
    isActive: true,
  },
  {
    resourceId: 'res_cbse_revision_math_calc_01',
    title: 'CBSE Revision Notes: Differentiation & Integration Fundamentals',
    description: 'Quick-revision formula sheet and worked examples for basic derivatives, limit definitions, and power rule integration.',
    resourceType: 'reference',
    subject: 'Mathematics',
    topic: 'Calculus',
    conceptId: 'concept_calculus_diff_01',
    classLevel: 12,
    board: 'CBSE',
    language: 'en',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    provider: 'CBSE Academic',
    officialSource: 'CBSE Senior Secondary Portal',
    sourceUrl: 'https://cbseacademic.nic.in/curriculum_2024.html',
    thumbnailUrl: 'https://cbseacademic.nic.in/images/cbse_logo.png',
    tags: ['calculus', 'differentiation', 'integration', 'revision_notes', 'prerequisite'],
    prerequisites: ['concept_poly_02'],
    learningObjectives: ['Apply power rule for derivatives', 'Solve basic definite integrals'],
    careerRelevance: ['Artificial Intelligence', 'Mechanical Engineering', 'Quantitative Finance'],
    examRelevance: ['CBSE Class 12 Board Exam', 'JEE Main Calculus'],
    isVerified: true,
    isActive: true,
  },
];
